python3 main.py agb &
python3 main.py ber1 &
python3 main.py ber2 &
python3 main.py ber3 &
python3 main.py bfe &
python3 main.py bn &
python3 main.py bre &
python3 main.py bs &
python3 main.py cgn1 &
python3 main.py cgn2 &
python3 main.py co &
python3 main.py da &
python3 main.py drs &
python3 main.py dtm &
python3 main.py dui &
python3 main.py dus &
python3 main.py erf &
python3 main.py ess &
python3 main.py ffm &
python3 main.py goe &
python3 main.py h &
python3 main.py hh &
python3 main.py ka &
python3 main.py ke &
python3 main.py ko &
python3 main.py lej &
python3 main.py md &
python3 main.py ms &
python3 main.py muc1 &
python3 main.py muc2 &
python3 main.py muc3 &
python3 main.py muc4 &
python3 main.py muc5 &
python3 main.py muc6 &
python3 main.py muc7 &
python3 main.py nue &
python3 main.py rgb &
python3 main.py sn &
python3 main.py str1 &
python3 main.py str2 &
python3 main.py ul &
python3 main.py wue &
nordvpn connect &